# 原因特定中
# 問題点 : APT が実行されない

# yml を変えるだけで解決する

# os:linux が必要 ?


# 新しいバージョンのcmakeが欲しいから xenial を使う
# cmake 3.12 以降が入っているはず
dist: xenial\
os: linux
language: cpp

sudo: required

compiler:
  - gcc
  - clang

env:
  global:
    - GTEST_COLOR=1
  matrix:
    - COMPILER=g++-5
    - COMPILER=clang++-7

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-7
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - clang-7
      - libgtest-dev

# addons:
#   apt:
#     # update: true # apt update をしてくれる
#     sources:
#       # 特定のg++のバージョンを入れるのに必要
#       # 実体は sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#       - ubuntu-toolchain-r-test
#       - llvm-toolchain-xenial-7
#         # - george-edison55-precise-backports # cmake 3.2 とかを入れるのに使う
#     packages:
#       - g++-5
#       - clang-7
#       - libgtest-dev
#       - python3-dev

# matrix:
#   include:
#     - compiler: gcc
#       env:
#         - COMPILER=g++-5
#     - compiler: clang
#       env:
#         - COMPILER=clang++-7

install:
  - pip install --user gcovr
  - pip install --user cpp-coveralls

before_script:
  - install -d gtest_build
  - pushd gtest_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER /usr/src/gtest/
  - make
  - sudo cp *.a /usr/lib
  - popd
  - rm gtest_build -rf

script:
  - cmake --version
  - install -d build
  - pushd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPIER ..
  - make VERBOSE=1

  # make test だと結果が表示されない
  # 失敗したものだけ表示するなら --output-on-failure
  - ctest -V

  # popするのは大事
  - popd

after_success:
  - coveralls -E ".*\/build\/.*" -E ".*\/test\/.*" --gcov-options '\-lp'

