# 新しいバージョンのcmakeが欲しいから xenial を使う
# cmake 3.12 以降が入っているはず

dist: xenial
language: cpp
sudo: required

compiler:
  - gcc
  - clang
os:
  - linux

addons:
  apt:
    # update: true # apt update をしてくれる
    sources:
      # 特定のg++のバージョンを入れるのに必要
      # 実体は sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
        # - george-edison55-precise-backports # cmake 3.2 とかを入れるのに使う
    packages:
      - g++-5
      - clang-7
      - libgtest-dev

matrix:
  include:
    - compiler: gcc
      env:
        - GTEST_COLOR=1
        - COMPILER=g++-5
    - compiler: clang
      env:
        - GTEST_COLOR=1
        - COMPILER=clang++-7

install:
  - pip install --user gcovr
  - pip install --user cpp-coveralls

before_script:
  - install -d gtest_build
  - pushd gtest_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER /usr/src/gtest/
  - make
  - sudo cp *.a /usr/lib
  - popd
  - rm gtest_build -rf

script:
  - cmake --version
  - install -d build
  - pushd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPIER ..
  - make VERBOSE=1

  # make test だと結果が表示されない
  # 失敗したものだけ表示するなら --output-on-failure
  - ctest -V

  # popするのは大事
  - popd

after_success:
  - coveralls -E ".*\/build\/.*" -E ".*\/test\/.*" --gcov-options '\-lp'

