language: cpp
sudo: required
# 新しいバージョンのcmakeが欲しいから xenial を使う
# cmake 3.12 以降が入っているはず
dist: xenial\

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          # update: true # apt update をしてくれる
          sources:
            # 特定のg++のバージョンを入れるのに必要
            # 実体は sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            - ubuntu-toolchain-r-test
            # - george-edison55-precise-backports # cmake 3.2 とかを入れるのに使う
          packages:
            - g++-5
            - libgtest-dev
            - python3-dev
      env:
        - COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libgtest-dev
      env:
        - COMPILER=clang++-7

before_install:
  - pip install --user gcovr
  - pip install --user cpp-coveralls

before_script:
  - sudo apt-get install libgtest-dev
  - install -d gtest_build
  - pushd gtest_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER /usr/src/gtest/
  - make
  - sudo cp *.a /usr/lib
  - rm gtest_build -rf
  - popd
script:
  - cmake --version
  - install -d build
  - pushd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPIER ..
  - make VERBOSE=1
  - make test VERBOSE=1
  # popするのは大事
  - popd
after_success:
  - coveralls --exclude build --exclude test --gcov-options '\-lp'

