language: cpp
sudo: required
# 新しいバージョンのcmakeが欲しいから xenial を使う
# cmake 3.12 以降が入っているはず
dist: xenial\

env:
  global:
    - GTEST_COLOR=1

addons:
  apt:
    # update: true # apt update をしてくれる
    sources:
      - llvm-toolchain-xenial-7
      # 特定のg++のバージョンを入れるのに必要
      # 実体は sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - ubuntu-toolchain-r-test
      # - george-edison55-precise-backports # cmake 3.2 とかを入れるのに使う
    packages:
      - clang-7
      - libgtest-dev

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-5
            - python3-dev
      env:
        - COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-7
      env:
        - COMPILER=clang++-7

before_install:
  - pip install --user gcovr
  - pip install --user cpp-coveralls

before_script:
  - install -d gtest_build
  - pushd gtest_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER /usr/src/gtest/
  - make
  - sudo cp *.a /usr/lib
  - rm gtest_build -rf
  - popd
script:
  - cmake --version
  - install -d build
  - pushd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPIER ..
  - make VERBOSE=1

  # make test だと結果が表示されない
  # 失敗したものだけ表示するなら --output-on-failure
  - ctest -V

  # popするのは大事
  - popd
after_success:
  - coveralls --exclude build --exclude test --gcov-options '\-lp'

