language: cpp
sudo: required
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
            # 特定のg++のバージョンを入れるのに必要
            # 実体は sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            - ubuntu-toolchain-r-test
            # - george-edison55-precise-backports
          packages:
            - g++-5
            # - cmake
            # - cmake-data
            - libgtest-dev
            - python3-dev
      env: COMPILER=g++-5
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.6
    #         - george-edison55-precise-backports
    #       packages:
    #         - clang-3.6
    #         - cmake
    #         - cmake-data
    #         - libgtest-dev
    #   env: COMPILER=clang++-3.6
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.7
    #         - george-edison55-precise-backports
    #       packages:
    #         - clang-3.7
    #         - cmake
    #         - cmake-data
    #         - libgtest-dev
    #   env: COMPILER=clang++-3.7

before_install:
  # - sudo apt install python
  - pip install --user gcovr
  - pip install --user cpp-coveralls
  # cmake
  - wget https://cmake.org/files/v3.4/cmake-3.4.0-rc3.tar.gz

before_script:
  - install -d gtest_build
  - pushd gtest_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER /usr/src/gtest/
  - make
  - sudo cp *.a /usr/lib
  - popd
script:
  - cmake --version
  - install -d build
  - cd build
  # - cmake -DCMAKE_CXX_COMPILER=$COMPIER -DPYTHON_LIBRARY=/usr/lib/python3.7 ..
  - cmake -DCMAKE_CXX_COMPILER=$COMPIER ..
  - make VERBOSE=1
  - make test
after_success:
  # - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
  - coveralls --gcov-options '\-lp'

